
import type { Metadata } from "next";
import { Noto_Sans_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const fontMono = Noto_Sans_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen w-full font-sans text-foreground bg-linear-to-b from-fuchsia-950 to-black antialiased",
          fontSans.variable
        )}>
        <Navbar />

        {children}
      <Footer />

      </body>
    </html>
  );
}
