
import type { Metadata } from "next";
import { Noto_Sans_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import IChat from "@/components/layout/ichat";
import SessionTimeout from "@/components/layout/SessionTimeout";
import { Toaster } from "@/components/ui/toaster";


export const fontMono = Noto_Sans_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "iSITE-PLUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning lang="en" className="dark">
      <body
        suppressHydrationWarning={true}
        className={clsx(
          "min-h-screen w-full font-sans text-foreground bg-gradient-to-b from-fuchsia-950 to-black antialiased",
          fontSans.variable,
        )}
      >
        {/* glowing backdrop */}
        <div className="absolute inset-0 -z-10 bg-fuchsia-glow" />

        {/* 🟣 Subtle animated glow overlay */}
        <div className="absolute inset-0 -z-10">
          <div className="absolute top-1/3 left-1/4  h-[500px] bg-purple-700/20 blur-[200px] rounded-full animate-pulse-slow" />
          <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-violet-600/20 blur-[180px] rounded-full animate-pulse-slow delay-1000" />
        </div>

        {/*<IChat />*/}
        <IChat />


        <div className="flex flex-col min-h-screen relative text-lg sm:text-xl">
          <Navbar />

          <main className="flex-grow flex flex-col justify-start pt-20 sm:pt-24 overflow-y-auto">
            {children}
          </main>

          <Footer />
        </div>
        <SessionTimeout />
        <Toaster />
      </body>
    </html>
  );
}
